apiVersion: constraints.gatekeeper.sh/v1beta1
kind: BlockExperimentalAlphaCrs
metadata:
  name: block-experimental-alpha-crs
spec:
  enforcementAction: deny
  match:
    kinds:
    - apiGroups:
      - extensions.istio.io
      kinds:
      - WasmPlugin
    - apiGroups:
      - telemetry.istio.io
      kinds:
      - Telemetry
