# Source: https://github.com/mathieu-benoit/istio-gatekeeper-demos
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: AllowedServicePortName
metadata:
  name: port-name-constraint
spec:
  enforcementAction: deny
  match:
    kinds:
    - apiGroups:
      - ""
      kinds:
      - Service
    excludedNamespaces:
    - kube-system
    - istio-ingress
    - istio-egress
    - default
    - kube-system
    - kube-node-lease
    - kube-public
  parameters:
    prefixes:
    - http
    - grpc
    - tcp
