apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  annotations:
    description: Block experimental and alpha custom resources.
  name: blockexperimentalalphacrs
spec:
  crd:
    spec:
      names:
        kind: BlockExperimentalAlphaCrs
  targets:
  - target: admission.k8s.gatekeeper.sh
    rego: |-
      package istio.guardrails.featurestatus

      violation[{"msg": msg}] {
        msg := sprintf("%v is experimental or alpha. Can only use beta or stable level APIs.", [input.review.kind.kind])
      }
