trigger:
  branches:
    include:
    - main
    - release-v*

pr:
  branches:
    include:
    - main
    - release-v*

stages:
- stage: build
  pool:
    vmImage: ubuntu-latest # Default agent pool for Azure Pipelines
  jobs:
    - job: build_docker_images
      steps:
      - bash: |
          echo "hello"
        displayName: Echo Hello
        workingDirectory: $(System.DefaultWorkingDirectory)
      - task: DockerInstaller@0
        inputs:
          dockerVersion: '17.09.0-ce' # string. Required. Docker Version. Default: 17.09.0-ce.
      - bash: |
          docker version
        displayName: Ensure docker installation succeeded
    