trigger:
  branches:
    include:
    - main
    - release-v*

pr:
  branches:
    include:
    - main
    - release-v*

variables:
  repo.path: $(System.DefaultWorkingDirectory)/osm
  repo.chart.path: $(repo.path)/charts/$(chart.name)
  image.artifact.name: drop
  image.tag: $(checkout.tag)
  KUBECONFIG: $(System.DefaultWorkingDirectory)/kubeconfig.json

stages:
- stage: build
  pool:
    vmImage: ubuntu-latest # Default agent pool for Azure Pipelines
  jobs:
    - job: build_docker_images
      steps:
      - task: DockerInstaller@0
        inputs:
          dockerVersion: '17.09.0-ce' # string. Required. Docker Version. Default: 17.09.0-ce.
      - bash: docker version
        displayName: Ensure docker installation succeeded
      - bash: docker login -u $(docker.username) -p "$DOCKER_PASSWORD"
        displayName: Login to docker registry.
        env:
          DOCKER_PASSWORD: $(docker.password)
      - template: ./templates/build-and-push-image.yaml
        parameters:
          image_registry: $(docker.username)
          image_name: client
          image_tag: test
          dockerfile_path: ./ado-pipeline-go-microservice-app/client
      - template: ./templates/build-and-push-image.yaml
        parameters:
          image_registry: $(docker.username)
          image_name: server
          image_tag: test
          dockerfile_path: ./ado-pipeline-go-microservice-app/server
      - template: ./templates/install-kind.yaml
        parameters:
          kind_version: 0.17.0
      - template: ./templates/create-kind-cluster.yaml
        parameters:
          cluster_name: kind-test
      - bash: kubectl get pods -A
        displayName: Get pods
