# From 
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-ratelimit-svc
  namespace: {{ .Values.ingressNamespace }}
spec:
  workloadSelector:
    labels:
    {{- range $key, $val := .Values.ingressSelector }}
      {{ $key }}: {{ $val }}
    {{- end }}
  configPatches:
    - applyTo: VIRTUAL_HOST
      match:
        context: GATEWAY
        routeConfiguration:
          vhost:
            name: {{ .Values.routeConfig.vhost | quote }}
            route:
              action: {{ .Values.routeConfig.routeAction }}
      patch:
        operation: MERGE
        # Applies the rate limit rules.
        value:
          rate_limits:
            - actions: # any actions in here
              - request_headers:
                {{- range $headers := .Values.routeConfig.requestHeaders }}
                  header_name: {{ $headers.headerName | quote }}
                  descriptor_key: {{ $headers.descriptorKey | quote }}
                {{- end }}
